"""Codex CLI adapter planning."""

from __future__ import annotations

from collections.abc import Mapping

from agent21.adapters.protocol import (
    AdapterContext,
    AgentCapability,
    PlannedArtifact,
    sorted_artifacts,
    transform_artifact,
)
from agent21.models import CapabilityStatus

AGENT = "codex"
DISPLAY_NAME = "Codex CLI"

capability = AgentCapability(
    agent=AGENT,
    instructions=CapabilityStatus.NATIVE,
    skills=CapabilityStatus.NATIVE,
    mcp=CapabilityStatus.TRANSFORM,
    implemented=True,
    executable="codex",
)


def plan(context: AdapterContext) -> tuple[PlannedArtifact, ...]:
    """规划 Codex 项目 MCP 配置；指令和 Skills 由 Codex 原生读取。"""
    if not context.mcp_servers:
        return ()
    return sorted_artifacts(
        [transform_artifact(AGENT, ".codex/config.toml", _codex_config_toml(context.mcp_servers))]
    )


def _codex_config_toml(servers: Mapping[str, Mapping[str, object]]) -> bytes:
    """生成 Codex CLI 官方 `mcp_servers.<name>` TOML 片段。"""
    lines = [
        "# Generated by agent21. Edit the project .mcp.json source instead.",
    ]
    for name in sorted(servers):
        lines.append("")
        lines.append(f"[mcp_servers.{_quote_toml_string(name)}]")
        for key, value in sorted(servers[name].items()):
            lines.append(f"{key} = {_toml_value(value)}")
    return ("\n".join(lines) + "\n").encode("utf-8")


def _toml_value(value: object) -> str:
    """编码 MVP 需要的 TOML 标量和字符串数组。"""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int | float) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, list) and all(isinstance(item, str) for item in value):
        return "[" + ", ".join(_quote_toml_string(item) for item in value) + "]"
    if isinstance(value, dict) and all(isinstance(key, str) for key in value):
        pairs = [f"{key} = {_toml_value(item)}" for key, item in sorted(value.items())]
        return "{ " + ", ".join(pairs) + " }"
    if isinstance(value, str):
        return _quote_toml_string(value)
    raise TypeError(f"unsupported MCP TOML value: {value!r}")


def _quote_toml_string(value: str) -> str:
    """用 JSON 字符串规则生成兼容 TOML 的基础字符串。"""
    import json

    return json.dumps(value, ensure_ascii=False)
